version: 2

models:
  - name: stg_order_header
    description: "Cleaned and standardized order header data"
    columns:
      - name: order_id
        description: "Unique order identifier"
        tests:
          - not_null
          - unique
          
      - name: truck_id
        description: "Food truck identifier"
        tests:
          - not_null
          
      - name: order_ts
        description: "Order timestamp"
        tests:
          - not_null
          
      - name: customer_id
        description: "Customer identifier"
        tests:
          - not_null
          
      - name: order_amount
        description: "Total order amount before discounts"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 10000
              inclusive: true
              
      - name: order_net_total
        description: "Final order amount after discounts and tax"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 10000
              inclusive: true

  - name: stg_order_details
    description: "Cleaned and standardized order line items"
    columns:
      - name: order_id
        description: "Unique order identifier"
        tests:
          - not_null
          - relationships:
              to: ref('stg_order_header')
              field: order_id
              
      - name: menu_item_id
        description: "Menu item identifier"
        tests:
          - not_null
          
      - name: quantity
        description: "Number of items ordered"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 100
              inclusive: true
              
      - name: price
        description: "Unit price"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1000
              inclusive: false
              
      - name: line_total
        description: "Total for this line item"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 10000
              inclusive: true
