name: 'tasty_bytes_dbt_demo'
version: '1.0.0'
config-version: 2

profile: 'tasty_bytes_dbt_demo'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  tasty_bytes_dbt_demo:
    staging:
      +materialized: view
      +tags: ['staging']
      
    marts:
      +materialized: table
      +tags: ['marts']

snapshots:
  +target_schema: snapshots
  +strategy: timestamp
  +unique_key: id
  +updated_at: updated_at
