name: 'tasty_bytes_dbt_demo'
version: '1.0.0'
config-version: 2

profile: 'tasty_bytes_dbt_demo'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  tasty_bytes_dbt_demo:
    +query_tag: dbt_{{ target.name }}_{{ model.name }}
    
    staging:
      +materialized: view
      +schema: staging
      +tags: ['staging']
      
    intermediate:
      +materialized: ephemeral
      +tags: ['intermediate']
      
    marts:
      +materialized: table
      +schema: marts
      +tags: ['marts']
      +post-hook:
        - "{{ log('Model ' ~ this ~ ' completed successfully', info=true) }}"

snapshots:
  +target_schema: snapshots
  +strategy: timestamp
  +unique_key: id
  +updated_at: updated_at

on-run-start:
  - "{{ log('Starting dbt run on target: ' ~ target.name, info=true) }}"
  
on-run-end:
  - "{{ log('Completed dbt run. Models built: ' ~ results|length, info=true) }}"
