version: 2

models:
  - name: sales_data_by_truck
    description: "Monthly aggregated sales data by truck brand, menu type, and item category"
    tests:
      - dbt_utils.expression_is_true:
          expression: "total_revenue > 0"
      - dbt_utils.expression_is_true:
          expression: "total_items_sold > 0"
      - dbt_utils.expression_is_true:
          expression: "total_orders > 0"
    columns:
      - name: truck_brand_name
        description: "Brand name of the food truck"
        tests:
          - not_null
          - accepted_values:
              values: ['Guac n Roll', 'Freezing Point', 'The Mac Shack', 'Cheeky Greek']
              
      - name: menu_type
        description: "Type of menu offered"
        tests:
          - not_null
          
      - name: item_category
        description: "Category of items sold"
        tests:
          - not_null
          
      - name: sales_month
        description: "First day of the month for sales aggregation"
        tests:
          - not_null
          
      - name: total_items_sold
        description: "Total quantity of items sold"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"
              
      - name: total_revenue
        description: "Total revenue in USD"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"
              
      - name: total_orders
        description: "Count of distinct orders"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"
